name: smart_task_manager
description: Smart Task Manager - voice controlled productivity app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.4.0
  provider: ^6.0.5
  speech_to_text: ^5.6.0
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

